// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package gfc.helloGRPC;

public interface requestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gfc.helloGRPC.request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
